// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConsoleURL() {
  return window['go']['main']['App']['ConsoleURL']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StartConsole() {
  return window['go']['main']['App']['StartConsole']();
}

export function StopConsole() {
  return window['go']['main']['App']['StopConsole']();
}
